###############################################################################
#                            Skrap-it Config Docker                           #
###############################################################################
version: "3.2"
networks:
    container_one:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
services:
    nginx:
        image: 'nginx:alpine'
        container_name: skrapit-webserver
        working_dir: /var/www
        restart: always
        volumes:
            - '.:/var/www'
            - './.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        networks:
            container_one:
                ipv4_address: 172.28.1.1
        ports:
            - '90:90'

    php-fpm:
        build: .docker/php-fpm
        container_name: skrapit-php-fpm
        working_dir: /var/www
        restart: always
        volumes:
            - '.:/var/www'
        links:
            - 'db:db'
        environment:
            - DOCKER_UID=1000
            - DOCKER_GID=1000
        networks:
            container_one:
                ipv4_address: 172.28.1.2

    db:
        image: 'mysql:5.7'
        container_name: skrapit-mysql
        restart: 'always'
        volumes:
            - '.docker/cache/:/var/lib/mysql'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        networks:
            container_one:
                ipv4_address: 172.28.1.3

    mailcatcher:
        image: 'dockage/mailcatcher:0.7.1'
        container_name: skrapit-mailcatcher
        restart: 'always'
        networks:
            container_one:
                ipv4_address: 172.28.1.4
        ports:
            - '1080:1080'

    phpmyadmin:
        image: 'phpmyadmin/phpmyadmin'
        container_name: skrapit-phpmyadmin
        links:
            - 'db:db'
        networks:
            container_one:
                ipv4_address: 172.28.1.5
        ports:
            - '8080:80'
