#!/usr/bin/env python3
intel = 'https://ark.intel.com'
base = 'https://ark.intel.com/content/www/us/en/ark/products/series/'

database_links = []
links = []
news_links = []

cpus = {
    'core': '122139/intel-core-processors.html',
    'xeon': '595/intel-xeon-processors.html',
    'xeon phi': '75557/intel-xeon-phi-processors.html',
    'atom': '29035/intel-atom-processor.html',
    'pentium': '29862/intel-pentium-processor.html',
    'celeron': '43521/intel-celeron-processor.html',
    'itanium': '451/intel-itanium-processor.html',
    'quark' : '79047/intel-quark-soc.html',
}

quantities = {
    'core': '',
    'xeon': '',
    'xeon phi': '',
    'atom': '',
    'pentium': '',
    'celeron': '',
    'itanium': '',
    'quark' : '',
}

specs = {
    'cores': 'CoreCount',
    'threads': 'ThreadCount',
    'lithography': 'Lithography',
    'segment': 'MarketSegment',
    'status': 'StatusCodeText',
    'launch': 'BornOnDate',
    'socket': 'SocketsSupported',
    'base_frequency': 'ClockSpeed',
    'boost_frequency': 'ClockSpeedMax',
    'burst_frequency': 'BurstFrequency',
    'thermal_velocity_boost_frequency': 'ThermalVelocityBoostFreq',
    'max_mem': 'MaxMem',
    'memory_types': 'MemoryTypes',
    'num_memory_channels': 'NumMemoryChannels',
    'max_memory_bandwidth': 'MaxMemoryBandwidth',
    'ecc_memory': 'ECCMemory',
    'processor_graphics_model_id': 'ProcessorGraphicsModelId',
    'graphics_freq': 'GraphicsFreq',
    'graphics_max_freq': 'GraphicsMaxFreq',
    'graphics_max_mem': 'GraphicsMaxMem',
    'graphics_output': 'GraphicsOutput',
    'graphics_4K_support_level': 'Graphics4KSupportLevel',
    'graphics_max_resolution_hdmi': 'GraphicsMaxResolutionHDMI',
    'graphics_max_resolution_dp': 'GraphicsMaxResolutionDP',
    'graphics_max_resoluion_vga': 'GraphicsMaxResoluionVGA',
    'graphics_directX_support': 'GraphicsDirectXSupport',
    'graphics_openGL_support': 'GraphicsOpenGLSupport',
    'quick_sync_video': 'QuickSyncVideo',
    'intru_3D': 'InTru3D',
    'clear_video_hd': 'CVTHD',
    'clear_video': 'ClearVideoTechnology',
    'num_displays_supported': 'NumDisplaysSupported',
    'scalable_sockets': 'ScalableSockets',
    'pci_express_revision': 'PCIExpressRevision',
    'pci_express_configs': 'PCIExpressConfigs',
    'num_pci_express_ports': 'NumPCIExpressPorts',
    'thermal_solution_specification': 'ThermalSolutionSpecification',
    't_case': 'TCase',
    'package_size': 'PackageSize',
    'optane_memory_support': 'OptaneMemorySupport',
    'turbo_boost_support': 'TBTVersion',
    'vpro_support': 'VProTechnology',
    'hyper_threading': 'HyperThreading',
    'virtualization_vtx': 'VTX',
    'virtualization_vtd': 'VTD',
    'extended_page_tables_vtx_ept': 'ExtendedPageTables',
    'transactional_sync_extensions': 'TransactionalSynchronizationExtensionVersion',
    'intel_64': 'EM64',
    'instruction_set': 'InstructionSet',
    'instruction_set_extensions': 'InstructionSetExtensions',
    'idle_states': 'HaltState',
    'speed_step_technology': 'SpeedstepTechnology',
    'thermal_monitoring_indicator': 'ThermalMonitoring2Indicator',
    'identity_protection_tech_version': 'IdentityProtectionTechVersion',
    'stable_image_platform_program_version': 'StableImagePlatformProgramVersion',
    'cache': 'Cache',
    'bus': 'Bus',
    'tdp': 'MaxTDP',
}

register = {
    'family': [],
    'name': [],
    'segment': [],
    'status': [],
    'launch': [],
    'socket': [],
    'cores': [],
    'threads': [],
    'lithography': [],
    'base_frequency': [],
    'boost_frequency': [],
    'burst_frequency': [],
    'thermal_velocity_boost_frequency': [],
    'max_mem': [],
    'memory_types': [],
    'num_memory_channels': [],
    'max_memory_bandwidth': [],
    'ecc_memory': [],
    'processor_graphics_model_id': [],
    'graphics_freq': [],
    'graphics_max_freq': [],
    'graphics_max_mem': [],
    'graphics_output': [],
    'graphics_4K_support_level': [],
    'graphics_max_resolution_hdmi': [],
    'graphics_max_resolution_dp': [],
    'graphics_max_resoluion_vga': [],
    'graphics_directX_support': [],
    'graphics_openGL_support': [],
    'quick_sync_video': [],
    'intru_3D': [],
    'clear_video_hd': [],
    'clear_video': [],
    'num_displays_supported': [],
    'scalable_sockets': [],
    'pci_express_revision': [],
    'pci_express_configs': [],
    'num_pci_express_ports': [],
    'thermal_solution_specification': [],
    't_case': [],
    'package_size': [],
    'optane_memory_support': [],
    'turbo_boost_support': [],
    'vpro_support': [],
    'hyper_threading': [],
    'virtualization_vtx': [],
    'virtualization_vtd': [],
    'extended_page_tables_vtx_ept': [],
    'transactional_sync_extensions': [],
    'intel_64': [],
    'instruction_set': [],
    'instruction_set_extensions': [],
    'idle_states': [],
    'speed_step_technology': [],
    'thermal_monitoring_indicator': [],
    'identity_protection_tech_version': [],
    'stable_image_platform_program_version': [],
    'cache': [],
    'bus': [],
    'tdp': [],
    'url': [],
}
